//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ModelServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelTag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelProperty))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.Model))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelTag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelProperty))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.Model))]
    public partial class EntityObject : WebApplication1.ModelServiceReference.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ModelServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ModelServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OOCEntityObject", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelTag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelProperty))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.Model))]
    public partial class OOCEntityObject : WebApplication1.ModelServiceReference.EntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelTag", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ModelTag : WebApplication1.ModelServiceReference.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parentTagGuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parentTagGuid {
            get {
                return this.parentTagGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.parentTagGuidField, value) != true)) {
                    this.parentTagGuidField = value;
                    this.RaisePropertyChanged("parentTagGuid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelProperty", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ModelProperty : WebApplication1.ModelServiceReference.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string additionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string defaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string additional {
            get {
                return this.additionalField;
            }
            set {
                if ((object.ReferenceEquals(this.additionalField, value) != true)) {
                    this.additionalField = value;
                    this.RaisePropertyChanged("additional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                if ((object.ReferenceEquals(this.defaultField, value) != true)) {
                    this.defaultField = value;
                    this.RaisePropertyChanged("default");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelGuid {
            get {
                return this.modelGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.modelGuidField, value) != true)) {
                    this.modelGuidField = value;
                    this.RaisePropertyChanged("modelGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Model : WebApplication1.ModelServiceReference.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string abstractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long authorUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isPublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string riverBasinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> topIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> typeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string versionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string @abstract {
            get {
                return this.abstractField;
            }
            set {
                if ((object.ReferenceEquals(this.abstractField, value) != true)) {
                    this.abstractField = value;
                    this.RaisePropertyChanged("abstract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long authorUserId {
            get {
                return this.authorUserIdField;
            }
            set {
                if ((this.authorUserIdField.Equals(value) != true)) {
                    this.authorUserIdField = value;
                    this.RaisePropertyChanged("authorUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                if ((object.ReferenceEquals(this.classNameField, value) != true)) {
                    this.classNameField = value;
                    this.RaisePropertyChanged("className");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eName {
            get {
                return this.eNameField;
            }
            set {
                if ((object.ReferenceEquals(this.eNameField, value) != true)) {
                    this.eNameField = value;
                    this.RaisePropertyChanged("eName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isApproved {
            get {
                return this.isApprovedField;
            }
            set {
                if ((this.isApprovedField.Equals(value) != true)) {
                    this.isApprovedField = value;
                    this.RaisePropertyChanged("isApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isPublic {
            get {
                return this.isPublicField;
            }
            set {
                if ((this.isPublicField.Equals(value) != true)) {
                    this.isPublicField = value;
                    this.RaisePropertyChanged("isPublic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string riverBasin {
            get {
                return this.riverBasinField;
            }
            set {
                if ((object.ReferenceEquals(this.riverBasinField, value) != true)) {
                    this.riverBasinField = value;
                    this.RaisePropertyChanged("riverBasin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> topId {
            get {
                return this.topIdField;
            }
            set {
                if ((this.topIdField.Equals(value) != true)) {
                    this.topIdField = value;
                    this.RaisePropertyChanged("topId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> typeId {
            get {
                return this.typeIdField;
            }
            set {
                if ((this.typeIdField.Equals(value) != true)) {
                    this.typeIdField = value;
                    this.RaisePropertyChanged("typeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                if ((object.ReferenceEquals(this.versionField, value) != true)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ModelServiceReference.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ModelServiceReference.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.Model))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.Model[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelTag[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelTag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelProperty[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.ModelProperty))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelServiceReference.EntityKeyMember[]))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelServiceReference.IModelService")]
    public interface IModelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/Create", ReplyAction="http://tempuri.org/IModelService/CreateResponse")]
        void Create(string name, string version, int authorUserId, string className, int topId, int typeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/GetByGuid", ReplyAction="http://tempuri.org/IModelService/GetByGuidResponse")]
        WebApplication1.ModelServiceReference.Model GetByGuid(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/ListByName", ReplyAction="http://tempuri.org/IModelService/ListByNameResponse")]
        WebApplication1.ModelServiceReference.Model[] ListByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/ListByAuthorUserId", ReplyAction="http://tempuri.org/IModelService/ListByAuthorUserIdResponse")]
        WebApplication1.ModelServiceReference.Model[] ListByAuthorUserId(int authorUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/ListByClassName", ReplyAction="http://tempuri.org/IModelService/ListByClassNameResponse")]
        WebApplication1.ModelServiceReference.Model[] ListByClassName(string className);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/ListByModelTags", ReplyAction="http://tempuri.org/IModelService/ListByModelTagsResponse")]
        WebApplication1.ModelServiceReference.Model[] ListByModelTags(WebApplication1.ModelServiceReference.ModelTag[] modelTags);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/Audit", ReplyAction="http://tempuri.org/IModelService/AuditResponse")]
        bool Audit(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/GetModelProperties", ReplyAction="http://tempuri.org/IModelService/GetModelPropertiesResponse")]
        WebApplication1.ModelServiceReference.ModelProperty[] GetModelProperties(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/AddModelProperty", ReplyAction="http://tempuri.org/IModelService/AddModelPropertyResponse")]
        void AddModelProperty(string guid, WebApplication1.ModelServiceReference.ModelProperty modelProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/RemoveModelProperty", ReplyAction="http://tempuri.org/IModelService/RemoveModelPropertyResponse")]
        void RemoveModelProperty(string guid, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/UpdateModelProperty", ReplyAction="http://tempuri.org/IModelService/UpdateModelPropertyResponse")]
        void UpdateModelProperty(string guid, string key, WebApplication1.ModelServiceReference.ModelProperty modelProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/ModelSimpleList", ReplyAction="http://tempuri.org/IModelService/ModelSimpleListResponse")]
        WebApplication1.ModelServiceReference.Model[] ModelSimpleList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/GetRiverBasinByModelGuid", ReplyAction="http://tempuri.org/IModelService/GetRiverBasinByModelGuidResponse")]
        WebApplication1.ModelServiceReference.ModelProperty GetRiverBasinByModelGuid(string modelGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/ModelSimpleListByTopID", ReplyAction="http://tempuri.org/IModelService/ModelSimpleListByTopIDResponse")]
        WebApplication1.ModelServiceReference.Model[] ModelSimpleListByTopID(int TypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/ModelSimpleListByTypeID", ReplyAction="http://tempuri.org/IModelService/ModelSimpleListByTypeIDResponse")]
        WebApplication1.ModelServiceReference.Model[] ModelSimpleListByTypeID(int TypeID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModelServiceChannel : WebApplication1.ModelServiceReference.IModelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelServiceClient : System.ServiceModel.ClientBase<WebApplication1.ModelServiceReference.IModelService>, WebApplication1.ModelServiceReference.IModelService {
        
        public ModelServiceClient() {
        }
        
        public ModelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(string name, string version, int authorUserId, string className, int topId, int typeId) {
            base.Channel.Create(name, version, authorUserId, className, topId, typeId);
        }
        
        public WebApplication1.ModelServiceReference.Model GetByGuid(string guid) {
            return base.Channel.GetByGuid(guid);
        }
        
        public WebApplication1.ModelServiceReference.Model[] ListByName(string name) {
            return base.Channel.ListByName(name);
        }
        
        public WebApplication1.ModelServiceReference.Model[] ListByAuthorUserId(int authorUserId) {
            return base.Channel.ListByAuthorUserId(authorUserId);
        }
        
        public WebApplication1.ModelServiceReference.Model[] ListByClassName(string className) {
            return base.Channel.ListByClassName(className);
        }
        
        public WebApplication1.ModelServiceReference.Model[] ListByModelTags(WebApplication1.ModelServiceReference.ModelTag[] modelTags) {
            return base.Channel.ListByModelTags(modelTags);
        }
        
        public bool Audit(string guid) {
            return base.Channel.Audit(guid);
        }
        
        public WebApplication1.ModelServiceReference.ModelProperty[] GetModelProperties(string guid) {
            return base.Channel.GetModelProperties(guid);
        }
        
        public void AddModelProperty(string guid, WebApplication1.ModelServiceReference.ModelProperty modelProperty) {
            base.Channel.AddModelProperty(guid, modelProperty);
        }
        
        public void RemoveModelProperty(string guid, string key) {
            base.Channel.RemoveModelProperty(guid, key);
        }
        
        public void UpdateModelProperty(string guid, string key, WebApplication1.ModelServiceReference.ModelProperty modelProperty) {
            base.Channel.UpdateModelProperty(guid, key, modelProperty);
        }
        
        public WebApplication1.ModelServiceReference.Model[] ModelSimpleList() {
            return base.Channel.ModelSimpleList();
        }
        
        public WebApplication1.ModelServiceReference.ModelProperty GetRiverBasinByModelGuid(string modelGuid) {
            return base.Channel.GetRiverBasinByModelGuid(modelGuid);
        }
        
        public WebApplication1.ModelServiceReference.Model[] ModelSimpleListByTopID(int TypeID) {
            return base.Channel.ModelSimpleListByTopID(TypeID);
        }
        
        public WebApplication1.ModelServiceReference.Model[] ModelSimpleListByTypeID(int TypeID) {
            return base.Channel.ModelSimpleListByTypeID(TypeID);
        }
    }
}
