//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.TaskProcessedDataSetServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskProcessedDataSetServiceReference.ITaskProcessedDataService")]
    public interface ITaskProcessedDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskProcessedDataService/CreateDataSet", ReplyAction="http://tempuri.org/ITaskProcessedDataService/CreateDataSetResponse")]
        string CreateDataSet(string taskGuid, string cmGuid, string className, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskProcessedDataService/RemoveDataSetByGuid", ReplyAction="http://tempuri.org/ITaskProcessedDataService/RemoveDataSetByGuidResponse")]
        void RemoveDataSetByGuid(string dataSetGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskProcessedDataService/GetDataSetByTaskGuid", ReplyAction="http://tempuri.org/ITaskProcessedDataService/GetDataSetByTaskGuidResponse")]
        OOC.Entity.TaskProcessedDataSet[] GetDataSetByTaskGuid(string taskGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskProcessedDataService/InsertIntoDataSet", ReplyAction="http://tempuri.org/ITaskProcessedDataService/InsertIntoDataSetResponse")]
        void InsertIntoDataSet(string dataSetGuid, string[] record);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskProcessedDataService/InsertMultipleIntoDataSet", ReplyAction="http://tempuri.org/ITaskProcessedDataService/InsertMultipleIntoDataSetResponse")]
        void InsertMultipleIntoDataSet(string dataSetGuid, string[][] records);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskProcessedDataService/QueryDataSetRecords", ReplyAction="http://tempuri.org/ITaskProcessedDataService/QueryDataSetRecordsResponse")]
        string[][] QueryDataSetRecords(string dataSetGuid, int start, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskProcessedDataService/QueryDataSet", ReplyAction="http://tempuri.org/ITaskProcessedDataService/QueryDataSetResponse")]
        OOC.Entity.TaskProcessedDataRecord[] QueryDataSet(string dataSetGuid, int start, int limit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskProcessedDataServiceChannel : WebApplication1.TaskProcessedDataSetServiceReference.ITaskProcessedDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskProcessedDataServiceClient : System.ServiceModel.ClientBase<WebApplication1.TaskProcessedDataSetServiceReference.ITaskProcessedDataService>, WebApplication1.TaskProcessedDataSetServiceReference.ITaskProcessedDataService {
        
        public TaskProcessedDataServiceClient() {
        }
        
        public TaskProcessedDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskProcessedDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskProcessedDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskProcessedDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateDataSet(string taskGuid, string cmGuid, string className, string name) {
            return base.Channel.CreateDataSet(taskGuid, cmGuid, className, name);
        }
        
        public void RemoveDataSetByGuid(string dataSetGuid) {
            base.Channel.RemoveDataSetByGuid(dataSetGuid);
        }
        
        public OOC.Entity.TaskProcessedDataSet[] GetDataSetByTaskGuid(string taskGuid) {
            return base.Channel.GetDataSetByTaskGuid(taskGuid);
        }
        
        public void InsertIntoDataSet(string dataSetGuid, string[] record) {
            base.Channel.InsertIntoDataSet(dataSetGuid, record);
        }
        
        public void InsertMultipleIntoDataSet(string dataSetGuid, string[][] records) {
            base.Channel.InsertMultipleIntoDataSet(dataSetGuid, records);
        }
        
        public string[][] QueryDataSetRecords(string dataSetGuid, int start, int limit) {
            return base.Channel.QueryDataSetRecords(dataSetGuid, start, limit);
        }
        
        public OOC.Entity.TaskProcessedDataRecord[] QueryDataSet(string dataSetGuid, int start, int limit) {
            return base.Channel.QueryDataSet(dataSetGuid, start, limit);
        }
    }
}
