//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOC.Instance.BillService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.Bill))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.Bill))]
    public partial class EntityObject : OOC.Instance.BillService.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.BillService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.BillService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OOCEntityObject", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.Bill))]
    public partial class OOCEntityObject : OOC.Instance.BillService.EntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bill", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Bill : OOC.Instance.BillService.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cmGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isRefundedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string taskGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cmGuid {
            get {
                return this.cmGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.cmGuidField, value) != true)) {
                    this.cmGuidField = value;
                    this.RaisePropertyChanged("cmGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isRefunded {
            get {
                return this.isRefundedField;
            }
            set {
                if ((this.isRefundedField.Equals(value) != true)) {
                    this.isRefundedField = value;
                    this.RaisePropertyChanged("isRefunded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string taskGuid {
            get {
                return this.taskGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.taskGuidField, value) != true)) {
                    this.taskGuidField = value;
                    this.RaisePropertyChanged("taskGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.BillService.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.BillService.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.Bill))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.Bill[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.BillService.StructuralObject))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BillService.IBillService")]
    public interface IBillService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Create", ReplyAction="http://tempuri.org/IBillService/CreateResponse")]
        void Create(int userId, string taskGuid, string cmGuid, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetById", ReplyAction="http://tempuri.org/IBillService/GetByIdResponse")]
        OOC.Instance.BillService.Bill GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetByUserId", ReplyAction="http://tempuri.org/IBillService/GetByUserIdResponse")]
        OOC.Instance.BillService.Bill[] GetByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetByTaskGuid", ReplyAction="http://tempuri.org/IBillService/GetByTaskGuidResponse")]
        OOC.Instance.BillService.Bill[] GetByTaskGuid(string taskGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetByCmGuid", ReplyAction="http://tempuri.org/IBillService/GetByCmGuidResponse")]
        OOC.Instance.BillService.Bill[] GetByCmGuid(string cmGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/Refund", ReplyAction="http://tempuri.org/IBillService/RefundResponse")]
        void Refund(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillServiceChannel : OOC.Instance.BillService.IBillService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillServiceClient : System.ServiceModel.ClientBase<OOC.Instance.BillService.IBillService>, OOC.Instance.BillService.IBillService {
        
        public BillServiceClient() {
        }
        
        public BillServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Create(int userId, string taskGuid, string cmGuid, double amount) {
            base.Channel.Create(userId, taskGuid, cmGuid, amount);
        }
        
        public OOC.Instance.BillService.Bill GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public OOC.Instance.BillService.Bill[] GetByUserId(int userId) {
            return base.Channel.GetByUserId(userId);
        }
        
        public OOC.Instance.BillService.Bill[] GetByTaskGuid(string taskGuid) {
            return base.Channel.GetByTaskGuid(taskGuid);
        }
        
        public OOC.Instance.BillService.Bill[] GetByCmGuid(string cmGuid) {
            return base.Channel.GetByCmGuid(cmGuid);
        }
        
        public void Refund(int id) {
            base.Channel.Refund(id);
        }
    }
}
