//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOC.Instance.TaskService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskState", Namespace="http://schemas.datacontract.org/2004/07/OOC.Contract.Data.Common")]
    public enum TaskState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PENDING = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WAITING = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASSIGNED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUNNING = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KILLED = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FINISHED = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/OOC.Contract.Data.Response")]
    [System.SerializableAttribute()]
    public partial class TaskInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.CompositionData CompositionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.Task TaskField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.CompositionData CompositionData {
            get {
                return this.CompositionDataField;
            }
            set {
                if ((object.ReferenceEquals(this.CompositionDataField, value) != true)) {
                    this.CompositionDataField = value;
                    this.RaisePropertyChanged("CompositionData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.Task Task {
            get {
                return this.TaskField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskField, value) != true)) {
                    this.TaskField = value;
                    this.RaisePropertyChanged("Task");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositionData", Namespace="http://schemas.datacontract.org/2004/07/OOC.Contract.Data.Common")]
    [System.SerializableAttribute()]
    public partial class CompositionData : OOC.Instance.TaskService.SerializableData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.Composition CompositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.CompositionLink[] LinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.CompositionModelData[] ModelsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.Composition Composition {
            get {
                return this.CompositionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompositionField, value) != true)) {
                    this.CompositionField = value;
                    this.RaisePropertyChanged("Composition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.CompositionLink[] Links {
            get {
                return this.LinksField;
            }
            set {
                if ((object.ReferenceEquals(this.LinksField, value) != true)) {
                    this.LinksField = value;
                    this.RaisePropertyChanged("Links");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.CompositionModelData[] Models {
            get {
                return this.ModelsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelsField, value) != true)) {
                    this.ModelsField = value;
                    this.RaisePropertyChanged("Models");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Task : OOC.Instance.TaskService.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string compositionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string compositionGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string instanceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelProgressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> timeFinishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> timeStartedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string compositionData {
            get {
                return this.compositionDataField;
            }
            set {
                if ((object.ReferenceEquals(this.compositionDataField, value) != true)) {
                    this.compositionDataField = value;
                    this.RaisePropertyChanged("compositionData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string compositionGuid {
            get {
                return this.compositionGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.compositionGuidField, value) != true)) {
                    this.compositionGuidField = value;
                    this.RaisePropertyChanged("compositionGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instanceName {
            get {
                return this.instanceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.instanceNameField, value) != true)) {
                    this.instanceNameField = value;
                    this.RaisePropertyChanged("instanceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelProgress {
            get {
                return this.modelProgressField;
            }
            set {
                if ((object.ReferenceEquals(this.modelProgressField, value) != true)) {
                    this.modelProgressField = value;
                    this.RaisePropertyChanged("modelProgress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> timeFinished {
            get {
                return this.timeFinishedField;
            }
            set {
                if ((this.timeFinishedField.Equals(value) != true)) {
                    this.timeFinishedField = value;
                    this.RaisePropertyChanged("timeFinished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> timeStarted {
            get {
                return this.timeStartedField;
            }
            set {
                if ((this.timeStartedField.Equals(value) != true)) {
                    this.timeStartedField = value;
                    this.RaisePropertyChanged("timeStarted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializableData", Namespace="http://schemas.datacontract.org/2004/07/OOC.Contract.Data.Abstract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionData))]
    public partial class SerializableData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Composition", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Composition : OOC.Instance.TaskService.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long authorUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isFinishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSharedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long authorUserId {
            get {
                return this.authorUserIdField;
            }
            set {
                if ((this.authorUserIdField.Equals(value) != true)) {
                    this.authorUserIdField = value;
                    this.RaisePropertyChanged("authorUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isFinished {
            get {
                return this.isFinishedField;
            }
            set {
                if ((this.isFinishedField.Equals(value) != true)) {
                    this.isFinishedField = value;
                    this.RaisePropertyChanged("isFinished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isShared {
            get {
                return this.isSharedField;
            }
            set {
                if ((this.isSharedField.Equals(value) != true)) {
                    this.isSharedField = value;
                    this.RaisePropertyChanged("isShared");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositionLink", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CompositionLink : OOC.Instance.TaskService.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string compositionGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sourceCmGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sourceElementSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sourceQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string targetCmGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string targetElementSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string targetQuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string compositionGuid {
            get {
                return this.compositionGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.compositionGuidField, value) != true)) {
                    this.compositionGuidField = value;
                    this.RaisePropertyChanged("compositionGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dataOperation {
            get {
                return this.dataOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.dataOperationField, value) != true)) {
                    this.dataOperationField = value;
                    this.RaisePropertyChanged("dataOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sourceCmGuid {
            get {
                return this.sourceCmGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceCmGuidField, value) != true)) {
                    this.sourceCmGuidField = value;
                    this.RaisePropertyChanged("sourceCmGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sourceElementSet {
            get {
                return this.sourceElementSetField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceElementSetField, value) != true)) {
                    this.sourceElementSetField = value;
                    this.RaisePropertyChanged("sourceElementSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sourceQuantity {
            get {
                return this.sourceQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceQuantityField, value) != true)) {
                    this.sourceQuantityField = value;
                    this.RaisePropertyChanged("sourceQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string targetCmGuid {
            get {
                return this.targetCmGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.targetCmGuidField, value) != true)) {
                    this.targetCmGuidField = value;
                    this.RaisePropertyChanged("targetCmGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string targetElementSet {
            get {
                return this.targetElementSetField;
            }
            set {
                if ((object.ReferenceEquals(this.targetElementSetField, value) != true)) {
                    this.targetElementSetField = value;
                    this.RaisePropertyChanged("targetElementSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string targetQuantity {
            get {
                return this.targetQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.targetQuantityField, value) != true)) {
                    this.targetQuantityField = value;
                    this.RaisePropertyChanged("targetQuantity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositionModelData", Namespace="http://schemas.datacontract.org/2004/07/OOC.Contract.Data.Common")]
    [System.SerializableAttribute()]
    public partial class CompositionModelData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.CompositionModel CompositionModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.Model ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.ModelFileMapping[] ModelFilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.CompositionModelProperties PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.CompositionModel CompositionModel {
            get {
                return this.CompositionModelField;
            }
            set {
                if ((object.ReferenceEquals(this.CompositionModelField, value) != true)) {
                    this.CompositionModelField = value;
                    this.RaisePropertyChanged("CompositionModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.Model Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.ModelFileMapping[] ModelFiles {
            get {
                return this.ModelFilesField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelFilesField, value) != true)) {
                    this.ModelFilesField = value;
                    this.RaisePropertyChanged("ModelFiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.CompositionModelProperties Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionLink))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Model))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.ModelFileMapping))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Task))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Composition))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionLink))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Model))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.ModelFileMapping))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Task))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Composition))]
    public partial class EntityObject : OOC.Instance.TaskService.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OOCEntityObject", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionLink))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Model))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.ModelFileMapping))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Task))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Composition))]
    public partial class OOCEntityObject : OOC.Instance.TaskService.EntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositionModel", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CompositionModel : OOC.Instance.TaskService.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string compositionGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string propertiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string compositionGuid {
            get {
                return this.compositionGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.compositionGuidField, value) != true)) {
                    this.compositionGuidField = value;
                    this.RaisePropertyChanged("compositionGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelGuid {
            get {
                return this.modelGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.modelGuidField, value) != true)) {
                    this.modelGuidField = value;
                    this.RaisePropertyChanged("modelGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string properties {
            get {
                return this.propertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.propertiesField, value) != true)) {
                    this.propertiesField = value;
                    this.RaisePropertyChanged("properties");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Model", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Model : OOC.Instance.TaskService.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string abstractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long authorUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isPublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string versionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string @abstract {
            get {
                return this.abstractField;
            }
            set {
                if ((object.ReferenceEquals(this.abstractField, value) != true)) {
                    this.abstractField = value;
                    this.RaisePropertyChanged("abstract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long authorUserId {
            get {
                return this.authorUserIdField;
            }
            set {
                if ((this.authorUserIdField.Equals(value) != true)) {
                    this.authorUserIdField = value;
                    this.RaisePropertyChanged("authorUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                if ((object.ReferenceEquals(this.classNameField, value) != true)) {
                    this.classNameField = value;
                    this.RaisePropertyChanged("className");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                if ((object.ReferenceEquals(this.guidField, value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isApproved {
            get {
                return this.isApprovedField;
            }
            set {
                if ((this.isApprovedField.Equals(value) != true)) {
                    this.isApprovedField = value;
                    this.RaisePropertyChanged("isApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isPublic {
            get {
                return this.isPublicField;
            }
            set {
                if ((this.isPublicField.Equals(value) != true)) {
                    this.isPublicField = value;
                    this.RaisePropertyChanged("isPublic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                if ((object.ReferenceEquals(this.versionField, value) != true)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelFileMapping", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ModelFileMapping : OOC.Instance.TaskService.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isDocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isMainLibraryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> modificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creation {
            get {
                return this.creationField;
            }
            set {
                if ((this.creationField.Equals(value) != true)) {
                    this.creationField = value;
                    this.RaisePropertyChanged("creation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isDocument {
            get {
                return this.isDocumentField;
            }
            set {
                if ((this.isDocumentField.Equals(value) != true)) {
                    this.isDocumentField = value;
                    this.RaisePropertyChanged("isDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isMainLibrary {
            get {
                return this.isMainLibraryField;
            }
            set {
                if ((this.isMainLibraryField.Equals(value) != true)) {
                    this.isMainLibraryField = value;
                    this.RaisePropertyChanged("isMainLibrary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modelGuid {
            get {
                return this.modelGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.modelGuidField, value) != true)) {
                    this.modelGuidField = value;
                    this.RaisePropertyChanged("modelGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> modification {
            get {
                return this.modificationField;
            }
            set {
                if ((this.modificationField.Equals(value) != true)) {
                    this.modificationField = value;
                    this.RaisePropertyChanged("modification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                if ((object.ReferenceEquals(this.signatureField, value) != true)) {
                    this.signatureField = value;
                    this.RaisePropertyChanged("signature");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OOC.Instance.TaskService.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OOC.Instance.TaskService.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.SerializableData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Dict))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Composition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionLink[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionLink))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Model))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.ModelFileMapping[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.ModelFileMapping))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.Task))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.TaskState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionModelData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionModelData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionModelProperties))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.TaskInfoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dict", Namespace="http://schemas.datacontract.org/2004/07/OOC.Contract.Data.Abstract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OOC.Instance.TaskService.CompositionModelProperties))]
    public partial class Dict : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> KvsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Kvs {
            get {
                return this.KvsField;
            }
            set {
                if ((object.ReferenceEquals(this.KvsField, value) != true)) {
                    this.KvsField = value;
                    this.RaisePropertyChanged("Kvs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositionModelProperties", Namespace="http://schemas.datacontract.org/2004/07/OOC.Contract.Data.Common")]
    [System.SerializableAttribute()]
    public partial class CompositionModelProperties : OOC.Instance.TaskService.Dict {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskService.ITaskService")]
    public interface ITaskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/Create", ReplyAction="http://tempuri.org/ITaskService/CreateResponse")]
        string Create(string compositionGuid, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/UpdateState", ReplyAction="http://tempuri.org/ITaskService/UpdateStateResponse")]
        void UpdateState(string guid, OOC.Instance.TaskService.TaskState state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/AssignPendingTask", ReplyAction="http://tempuri.org/ITaskService/AssignPendingTaskResponse")]
        OOC.Instance.TaskService.TaskInfoResponse AssignPendingTask(string instanceName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/QueryTaskByGuid", ReplyAction="http://tempuri.org/ITaskService/QueryTaskByGuidResponse")]
        OOC.Instance.TaskService.TaskInfoResponse QueryTaskByGuid(string guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskServiceChannel : OOC.Instance.TaskService.ITaskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskServiceClient : System.ServiceModel.ClientBase<OOC.Instance.TaskService.ITaskService>, OOC.Instance.TaskService.ITaskService {
        
        public TaskServiceClient() {
        }
        
        public TaskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Create(string compositionGuid, int userId) {
            return base.Channel.Create(compositionGuid, userId);
        }
        
        public void UpdateState(string guid, OOC.Instance.TaskService.TaskState state) {
            base.Channel.UpdateState(guid, state);
        }
        
        public OOC.Instance.TaskService.TaskInfoResponse AssignPendingTask(string instanceName) {
            return base.Channel.AssignPendingTask(instanceName);
        }
        
        public OOC.Instance.TaskService.TaskInfoResponse QueryTaskByGuid(string guid) {
            return base.Channel.QueryTaskByGuid(guid);
        }
    }
}
