//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ModelTypeServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelTypeServiceReference.IModelTypeService")]
    public interface IModelTypeService {
        
        // CODEGEN: Parameter 'GetTypeListResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTypeList", ReplyAction="http://tempuri.org/IModelTypeService/GetTypeListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        WebApplication1.ModelTypeServiceReference.GetTypeListResponse GetTypeList(WebApplication1.ModelTypeServiceReference.GetTypeListRequest request);
        
        // CODEGEN: Parameter 'GetTypeListDSResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTypeListDS", ReplyAction="http://tempuri.org/IModelTypeService/GetTypeListDSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        WebApplication1.ModelTypeServiceReference.GetTypeListDSResponse GetTypeListDS(WebApplication1.ModelTypeServiceReference.GetTypeListDSRequest request);
        
        // CODEGEN: Parameter 'GetTopListResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTopList", ReplyAction="http://tempuri.org/IModelTypeService/GetTopListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        WebApplication1.ModelTypeServiceReference.GetTopListResponse GetTopList(WebApplication1.ModelTypeServiceReference.GetTopListRequest request);
        
        // CODEGEN: Parameter 'GetSubByTopIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetSubByTopID", ReplyAction="http://tempuri.org/IModelTypeService/GetSubByTopIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        WebApplication1.ModelTypeServiceReference.GetSubByTopIDResponse GetSubByTopID(WebApplication1.ModelTypeServiceReference.GetSubByTopIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/IsTopType", ReplyAction="http://tempuri.org/IModelTypeService/IsTopTypeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool IsTopType(int TypeID);
        
        // CODEGEN: Parameter 'GetTypeByIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTypeByID", ReplyAction="http://tempuri.org/IModelTypeService/GetTypeByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        WebApplication1.ModelTypeServiceReference.GetTypeByIDResponse GetTypeByID(WebApplication1.ModelTypeServiceReference.GetTypeByIDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity")]
    public partial class ModelType : OOCEntityObject {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool isSubField;
        
        private bool isSubFieldSpecified;
        
        private bool isTopField;
        
        private bool isTopFieldSpecified;
        
        private string notesField;
        
        private System.Nullable<int> topIdField;
        
        private bool topIdFieldSpecified;
        
        private string typeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool isSub {
            get {
                return this.isSubField;
            }
            set {
                this.isSubField = value;
                this.RaisePropertyChanged("isSub");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSubSpecified {
            get {
                return this.isSubFieldSpecified;
            }
            set {
                this.isSubFieldSpecified = value;
                this.RaisePropertyChanged("isSubSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool isTop {
            get {
                return this.isTopField;
            }
            set {
                this.isTopField = value;
                this.RaisePropertyChanged("isTop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isTopSpecified {
            get {
                return this.isTopFieldSpecified;
            }
            set {
                this.isTopFieldSpecified = value;
                this.RaisePropertyChanged("isTopSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> topId {
            get {
                return this.topIdField;
            }
            set {
                this.topIdField = value;
                this.RaisePropertyChanged("topId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool topIdSpecified {
            get {
                return this.topIdFieldSpecified;
            }
            set {
                this.topIdFieldSpecified = value;
                this.RaisePropertyChanged("topIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
                this.RaisePropertyChanged("typeName");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity")]
    public partial class OOCEntityObject : EntityObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OOCEntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        private string entitySetNameField;
        
        private string idField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/", DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/", DataType="IDREF")]
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("Ref");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OOCEntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/", DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/", DataType="IDREF")]
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("Ref");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTypeList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTypeListRequest {
        
        public GetTypeListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTypeListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTypeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity")]
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetTypeListResult;
        
        public GetTypeListResponse() {
        }
        
        public GetTypeListResponse(WebApplication1.ModelTypeServiceReference.ModelType[] GetTypeListResult) {
            this.GetTypeListResult = GetTypeListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTypeListDS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTypeListDSRequest {
        
        public GetTypeListDSRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTypeListDSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTypeListDSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetTypeListDSResult;
        
        public GetTypeListDSResponse() {
        }
        
        public GetTypeListDSResponse(System.Data.DataSet GetTypeListDSResult) {
            this.GetTypeListDSResult = GetTypeListDSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopListRequest {
        
        public GetTopListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTopListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity")]
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetTopListResult;
        
        public GetTopListResponse() {
        }
        
        public GetTopListResponse(WebApplication1.ModelTypeServiceReference.ModelType[] GetTopListResult) {
            this.GetTopListResult = GetTopListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubByTopID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubByTopIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int TopID;
        
        public GetSubByTopIDRequest() {
        }
        
        public GetSubByTopIDRequest(int TopID) {
            this.TopID = TopID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubByTopIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSubByTopIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity")]
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetSubByTopIDResult;
        
        public GetSubByTopIDResponse() {
        }
        
        public GetSubByTopIDResponse(WebApplication1.ModelTypeServiceReference.ModelType[] GetSubByTopIDResult) {
            this.GetSubByTopIDResult = GetSubByTopIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTypeByID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTypeByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ID;
        
        public GetTypeByIDRequest() {
        }
        
        public GetTypeByIDRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTypeByIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTypeByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebApplication1.ModelTypeServiceReference.ModelType GetTypeByIDResult;
        
        public GetTypeByIDResponse() {
        }
        
        public GetTypeByIDResponse(WebApplication1.ModelTypeServiceReference.ModelType GetTypeByIDResult) {
            this.GetTypeByIDResult = GetTypeByIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModelTypeServiceChannel : WebApplication1.ModelTypeServiceReference.IModelTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelTypeServiceClient : System.ServiceModel.ClientBase<WebApplication1.ModelTypeServiceReference.IModelTypeService>, WebApplication1.ModelTypeServiceReference.IModelTypeService {
        
        public ModelTypeServiceClient() {
        }
        
        public ModelTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ModelTypeServiceReference.GetTypeListResponse WebApplication1.ModelTypeServiceReference.IModelTypeService.GetTypeList(WebApplication1.ModelTypeServiceReference.GetTypeListRequest request) {
            return base.Channel.GetTypeList(request);
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetTypeList() {
            WebApplication1.ModelTypeServiceReference.GetTypeListRequest inValue = new WebApplication1.ModelTypeServiceReference.GetTypeListRequest();
            WebApplication1.ModelTypeServiceReference.GetTypeListResponse retVal = ((WebApplication1.ModelTypeServiceReference.IModelTypeService)(this)).GetTypeList(inValue);
            return retVal.GetTypeListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ModelTypeServiceReference.GetTypeListDSResponse WebApplication1.ModelTypeServiceReference.IModelTypeService.GetTypeListDS(WebApplication1.ModelTypeServiceReference.GetTypeListDSRequest request) {
            return base.Channel.GetTypeListDS(request);
        }
        
        public System.Data.DataSet GetTypeListDS() {
            WebApplication1.ModelTypeServiceReference.GetTypeListDSRequest inValue = new WebApplication1.ModelTypeServiceReference.GetTypeListDSRequest();
            WebApplication1.ModelTypeServiceReference.GetTypeListDSResponse retVal = ((WebApplication1.ModelTypeServiceReference.IModelTypeService)(this)).GetTypeListDS(inValue);
            return retVal.GetTypeListDSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ModelTypeServiceReference.GetTopListResponse WebApplication1.ModelTypeServiceReference.IModelTypeService.GetTopList(WebApplication1.ModelTypeServiceReference.GetTopListRequest request) {
            return base.Channel.GetTopList(request);
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetTopList() {
            WebApplication1.ModelTypeServiceReference.GetTopListRequest inValue = new WebApplication1.ModelTypeServiceReference.GetTopListRequest();
            WebApplication1.ModelTypeServiceReference.GetTopListResponse retVal = ((WebApplication1.ModelTypeServiceReference.IModelTypeService)(this)).GetTopList(inValue);
            return retVal.GetTopListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ModelTypeServiceReference.GetSubByTopIDResponse WebApplication1.ModelTypeServiceReference.IModelTypeService.GetSubByTopID(WebApplication1.ModelTypeServiceReference.GetSubByTopIDRequest request) {
            return base.Channel.GetSubByTopID(request);
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetSubByTopID(int TopID) {
            WebApplication1.ModelTypeServiceReference.GetSubByTopIDRequest inValue = new WebApplication1.ModelTypeServiceReference.GetSubByTopIDRequest();
            inValue.TopID = TopID;
            WebApplication1.ModelTypeServiceReference.GetSubByTopIDResponse retVal = ((WebApplication1.ModelTypeServiceReference.IModelTypeService)(this)).GetSubByTopID(inValue);
            return retVal.GetSubByTopIDResult;
        }
        
        public bool IsTopType(int TypeID) {
            return base.Channel.IsTopType(TypeID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.ModelTypeServiceReference.GetTypeByIDResponse WebApplication1.ModelTypeServiceReference.IModelTypeService.GetTypeByID(WebApplication1.ModelTypeServiceReference.GetTypeByIDRequest request) {
            return base.Channel.GetTypeByID(request);
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType GetTypeByID(int ID) {
            WebApplication1.ModelTypeServiceReference.GetTypeByIDRequest inValue = new WebApplication1.ModelTypeServiceReference.GetTypeByIDRequest();
            inValue.ID = ID;
            WebApplication1.ModelTypeServiceReference.GetTypeByIDResponse retVal = ((WebApplication1.ModelTypeServiceReference.IModelTypeService)(this)).GetTypeByID(inValue);
            return retVal.GetTypeByIDResult;
        }
    }
}
