//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ModelTypeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelType", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ModelType : WebApplication1.ModelTypeServiceReference.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isTopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> topIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSub {
            get {
                return this.isSubField;
            }
            set {
                if ((this.isSubField.Equals(value) != true)) {
                    this.isSubField = value;
                    this.RaisePropertyChanged("isSub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isTop {
            get {
                return this.isTopField;
            }
            set {
                if ((this.isTopField.Equals(value) != true)) {
                    this.isTopField = value;
                    this.RaisePropertyChanged("isTop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> topId {
            get {
                return this.topIdField;
            }
            set {
                if ((this.topIdField.Equals(value) != true)) {
                    this.topIdField = value;
                    this.RaisePropertyChanged("topId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.typeNameField, value) != true)) {
                    this.typeNameField = value;
                    this.RaisePropertyChanged("typeName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType))]
    public partial class EntityObject : WebApplication1.ModelTypeServiceReference.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ModelTypeServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ModelTypeServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OOCEntityObject", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType))]
    public partial class OOCEntityObject : WebApplication1.ModelTypeServiceReference.EntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ModelTypeServiceReference.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ModelTypeServiceReference.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.OOCEntityObject))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelTypeServiceReference.IModelTypeService")]
    public interface IModelTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTypeList", ReplyAction="http://tempuri.org/IModelTypeService/GetTypeListResponse")]
        WebApplication1.ModelTypeServiceReference.ModelType[] GetTypeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTypeListDS", ReplyAction="http://tempuri.org/IModelTypeService/GetTypeListDSResponse")]
        System.Data.DataSet GetTypeListDS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTopList", ReplyAction="http://tempuri.org/IModelTypeService/GetTopListResponse")]
        WebApplication1.ModelTypeServiceReference.ModelType[] GetTopList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetSubByTopID", ReplyAction="http://tempuri.org/IModelTypeService/GetSubByTopIDResponse")]
        WebApplication1.ModelTypeServiceReference.ModelType[] GetSubByTopID(int TopID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/IsTopType", ReplyAction="http://tempuri.org/IModelTypeService/IsTopTypeResponse")]
        bool IsTopType(int TypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTypeByID", ReplyAction="http://tempuri.org/IModelTypeService/GetTypeByIDResponse")]
        WebApplication1.ModelTypeServiceReference.ModelType GetTypeByID(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModelTypeServiceChannel : WebApplication1.ModelTypeServiceReference.IModelTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelTypeServiceClient : System.ServiceModel.ClientBase<WebApplication1.ModelTypeServiceReference.IModelTypeService>, WebApplication1.ModelTypeServiceReference.IModelTypeService {
        
        public ModelTypeServiceClient() {
        }
        
        public ModelTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetTypeList() {
            return base.Channel.GetTypeList();
        }
        
        public System.Data.DataSet GetTypeListDS() {
            return base.Channel.GetTypeListDS();
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetTopList() {
            return base.Channel.GetTopList();
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetSubByTopID(int TopID) {
            return base.Channel.GetSubByTopID(TopID);
        }
        
        public bool IsTopType(int TypeID) {
            return base.Channel.IsTopType(TypeID);
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType GetTypeByID(int ID) {
            return base.Channel.GetTypeByID(ID);
        }
    }
}
