//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ModelTypeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelType", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ModelType : WebApplication1.ModelTypeServiceReference.OOCEntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TopIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSub {
            get {
                return this.IsSubField;
            }
            set {
                if ((this.IsSubField.Equals(value) != true)) {
                    this.IsSubField = value;
                    this.RaisePropertyChanged("IsSub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTop {
            get {
                return this.IsTopField;
            }
            set {
                if ((this.IsTopField.Equals(value) != true)) {
                    this.IsTopField = value;
                    this.RaisePropertyChanged("IsTop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TopID {
            get {
                return this.TopIDField;
            }
            set {
                if ((this.TopIDField.Equals(value) != true)) {
                    this.TopIDField = value;
                    this.RaisePropertyChanged("TopID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.OOCEntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType))]
    public partial class EntityObject : WebApplication1.ModelTypeServiceReference.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ModelTypeServiceReference.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ModelTypeServiceReference.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OOCEntityObject", Namespace="http://schemas.datacontract.org/2004/07/OOC.Entity", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType))]
    public partial class OOCEntityObject : WebApplication1.ModelTypeServiceReference.EntityObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApplication1.ModelTypeServiceReference.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApplication1.ModelTypeServiceReference.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.ModelType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ModelTypeServiceReference.OOCEntityObject))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelTypeServiceReference.IModelTypeService")]
    public interface IModelTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTypeList", ReplyAction="http://tempuri.org/IModelTypeService/GetTypeListResponse")]
        WebApplication1.ModelTypeServiceReference.ModelType[] GetTypeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTypeListDS", ReplyAction="http://tempuri.org/IModelTypeService/GetTypeListDSResponse")]
        System.Data.DataSet GetTypeListDS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTopList", ReplyAction="http://tempuri.org/IModelTypeService/GetTopListResponse")]
        WebApplication1.ModelTypeServiceReference.ModelType[] GetTopList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetSubByTopID", ReplyAction="http://tempuri.org/IModelTypeService/GetSubByTopIDResponse")]
        WebApplication1.ModelTypeServiceReference.ModelType[] GetSubByTopID(int TopID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/IsTopType", ReplyAction="http://tempuri.org/IModelTypeService/IsTopTypeResponse")]
        bool IsTopType(int TypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelTypeService/GetTypeByID", ReplyAction="http://tempuri.org/IModelTypeService/GetTypeByIDResponse")]
        WebApplication1.ModelTypeServiceReference.ModelType GetTypeByID(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModelTypeServiceChannel : WebApplication1.ModelTypeServiceReference.IModelTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelTypeServiceClient : System.ServiceModel.ClientBase<WebApplication1.ModelTypeServiceReference.IModelTypeService>, WebApplication1.ModelTypeServiceReference.IModelTypeService {
        
        public ModelTypeServiceClient() {
        }
        
        public ModelTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetTypeList() {
            return base.Channel.GetTypeList();
        }
        
        public System.Data.DataSet GetTypeListDS() {
            return base.Channel.GetTypeListDS();
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetTopList() {
            return base.Channel.GetTopList();
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType[] GetSubByTopID(int TopID) {
            return base.Channel.GetSubByTopID(TopID);
        }
        
        public bool IsTopType(int TypeID) {
            return base.Channel.IsTopType(TypeID);
        }
        
        public WebApplication1.ModelTypeServiceReference.ModelType GetTypeByID(int ID) {
            return base.Channel.GetTypeByID(ID);
        }
    }
}
